options(conflicts.policy = list(warn = FALSE))

suppressPackageStartupMessages({
  library(Matrix)
  library(countrycode)
  library(geodata)
  library(here)
  library(httr2)
  library(terra)
  library(tidyr)
  library(tibble)
  library(purrr)
  library(dplyr)
  library(magrittr)
})

here::i_am("loadDataForExamplesInteractive.R")
subregionsSpatVector <- terra::vect("~/src/r/spatialEpisim.foundation/inst/extdata/subregionsSpatVector")
susceptibleSpatRaster <- terra::rast("~/src/r/spatialEpisim.foundation/inst/extdata/susceptibleSpatRaster.tif")
data("healthZonesCongo")
data("initialInfections.fourCities")
data("Congo.EbolaIncidence")
source(here::here("R", "SVEIRD.BayesianDataAssimilation.R"))
layers <- getSVEIRD.SpatRaster(subregionsSpatVector, susceptibleSpatRaster, 35)
